# Generated by Django 4.2.7 on 2023-12-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='content',
            field=models.TextField(default='Default content'),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='published_date',
            field=models.DateField(auto_now=True),
        ),
    ]
