# Generated by Django 4.2.7 on 2023-12-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_alter_redactor_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='references',
            field=models.TextField(default='Default content'),
        ),
    ]
