# Generated by Django 4.2.7 on 2023-12-07 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper", "0004_newspaper_references"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={"ordering": ["topic__name"]},
        ),
    ]
